database/migrations/2023_07_11_111817_create_users_table.php, database/migrations/2023_07_11_112010_create_seminars_table.php, database/migrations/2023_07_11_112147_create_posts_table.php, database/migrations/2023_07_11_112339_create_members_table.php, database/migrations/2023_07_11_112426_create_committees_table.php, database/migrations/2023_07_11_112457_create_committee_members_table.php, database/migrations/2023_07_11_112742_create_files_table.php, package-lock.json, package.json, postcss.config.js, resources/css/app.css, tailwind.config.js
=> ✨ feat : Implement migration code & Install tailwindcss

app/Http/Controllers/CommitteeController.php, app/Models/Committee.php, app/Models/CommitteeMember.php, app/Models/Member.php, routes/api.php
=> ✨ feat : Implement Member Information API

database/migrations/2023_07_21_054121_create_forum_introduce_table.php, database/migrations/2023_07_21_054344_create_histories_table.php, database/migrations/2023_07_21_054458_create_contacts_table.php, database/migrations/2023_07_21_054610_create_business_table.php
`forum_introduce`, `histories`, `contacts`, `business` 테이블의 마이그레이션 작성
=> feat(migration): add migration code for forum_introduce, histories, contacts, business tables

app/Http/Controllers/BusinessController.php, app/Models/Business.php, routes/api.php
=> ✨ feat : Implement Business logic

app/Http/Controllers/BusinessController.php, routes/api.php
=> ✨ feat : Implement Business CRUD API

app/Http/Controllers/CommitteeController.php, routes/api.php
- `위원회`, `위원회 멤버` CRUD API 구현
- `위원회 멤버 조회` API는 `위원회 조회` API로 대체할 수 있으므로 미구현했습니다.
=> ✨ feat : Implement Committee & CommitteeMember CRUD API

app/Http/Kernel.php, app/Http/Middleware/AdminMiddleware.php, app/Models/User.php, routes/api.php
- `admin` 미들웨어 구현 및 적용
- `관리자 페이지` 미구현으로 아직 테스트해보진 못했으니 구현 이후 테스트 부탁드립니다.
=> ✨ feat : Implement Admin middleware

app/Http/Controllers/AboutUsController.php, app/Http/Controllers/BusinessController.php, app/Http/Controllers/FileController.php, app/Http/Controllers/HistoriesController.php, app/Http/Controllers/SeminarController.php, app/Models/AboutUs.php, app/Models/Histories.php, app/Models/Seminar.php, composer.json, composer.lock, routes/api.php
- add controllers
-  connect API endpoints for controller
=> feat: add Conrollers for AboutUs and Seminars, File

.gitignore, app/Http/Controllers/FileController.php
- add logic to upload file to s3 and return cloudfront url 
- add .env.development to ignore
=> feat: upload the file and receive the CloudFront URL instead of the AWS S3 URL.

app/Http/Controllers/SeminarController.php, app/Models/Seminar.php, routes/api.php
- add pagination function
- add search function
=> feat(board): Add search function

app/Http/Controllers/SeminarController.php
=> refactor(board): Modify sorting logic

.dockerignore, Dockerfile, routes/api.php
- add dockerfile, dockerignore files
- fixed route name
=> ci: Add Docker configuration for CI/CD

app/Http/Controllers/PostController.php, app/Http/Controllers/ReferenceController.php, app/Models/Post.php, routes/api.php
- create reference api
- create post model
=> feat(reference): Create reference api

app/Http/Controllers/CommitteeController.php, app/Http/Controllers/CommitteeMemberController.php, app/Http/Controllers/MemberController.php, app/Http/Controllers/UserController.php, app/Models/Committee.php, app/Models/Member.php, app/Providers/RouteServiceProvider.php, composer.lock, database/migrations/2023_08_29_165528_add_cascade_to_committee_members_table.php, routes/api.php
- Update foreign key constraints in committee_members table
- Committee API
- Committee_member API
- Member API
- Committee model
=> feat: Implement Committee API, Committee_member API, Member API

app/Http/Controllers/PostController.php, app/Http/Controllers/SeminarController.php, app/Models/File.php, routes/api.php
- add file attachment logic
- remove unnecessary route
=> feat(file): add file logic

app/Http/Controllers/AboutUsController.php, app/Models/AboutUs.php, database/migrations/2023_09_03_115105_add_chairman_to_forum_introduce_table.php
- add migration for add chairman related column to forum_introduce
- fix AboutUsController; showGreetings function included information about the chairman
=> feat(aboutus/greetings): Add information about the chairman to aboutus/greetings

app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/Auth/RefreshTokenController.php, app/Http/Controllers/Auth/RegisterController.php, app/Models/Member.php, app/Models/Post.php, composer.json, composer.lock, config/auth.php
- implement date format method
- modify login/register logic for the current
=> refactor(login): modify login/register logic for the current

app/Http/Controllers/Auth/LogoutController.php
- modify removing token method
=> refactor(logout): modify removing token method

app/Http/Controllers/MemberController.php, app/Http/Middleware/AdminMiddleware.php, routes/api.php
- implement return user profile method
- modify comment to english
=> feat(member): implement return user profile method

app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/CommitteeMemberController.php, app/Http/Controllers/FileController.php, app/Http/Controllers/MemberController.php, app/Http/Middleware/AdminMiddleware.php, app/Models/CommitteeMember.php, app/Models/Member.php, database/migrations/2023_09_07_024420_add_default_value_to_note_column_in_members_table.php, database/migrations/2023_09_07_024549_add_default_value_to_note_column_in_committee_members_table.php, database/migrations/2023_09_09_103908_alter_columns_of_members_table.php, routes/api.php
- Implement multiple deletion
#refactor
- refactor AdminMiddleware to use JWT authentication
...etc
=> Implement multiple deletion, refactor AdminMiddleware to use JWT authentication
